<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Gallery', 'doctrine');

/**
 * BaseGallery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idgallery
 * @property string $name
 * @property string $url
 * 
 * @method integer getIdgallery() Returns the current record's "idgallery" value
 * @method string  getName()      Returns the current record's "name" value
 * @method string  getUrl()       Returns the current record's "url" value
 * @method Gallery setIdgallery() Sets the current record's "idgallery" value
 * @method Gallery setName()      Sets the current record's "name" value
 * @method Gallery setUrl()       Sets the current record's "url" value
 * 
 * @package    hoanglong
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGallery extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gallery');
        $this->hasColumn('idgallery', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('url', 'string', 120, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'gallery.jpg',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 120,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}