<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CategoryVideo', 'doctrine');

/**
 * BaseCategoryVideo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idcategory_video
 * @property string $name
 * @property string $description
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $Video
 * 
 * @method integer             getIdcategoryVideo()  Returns the current record's "idcategory_video" value
 * @method string              getName()             Returns the current record's "name" value
 * @method string              getDescription()      Returns the current record's "description" value
 * @method timestamp           getCreatedAt()        Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()        Returns the current record's "updated_at" value
 * @method Doctrine_Collection getVideo()            Returns the current record's "Video" collection
 * @method CategoryVideo       setIdcategoryVideo()  Sets the current record's "idcategory_video" value
 * @method CategoryVideo       setName()             Sets the current record's "name" value
 * @method CategoryVideo       setDescription()      Sets the current record's "description" value
 * @method CategoryVideo       setCreatedAt()        Sets the current record's "created_at" value
 * @method CategoryVideo       setUpdatedAt()        Sets the current record's "updated_at" value
 * @method CategoryVideo       setVideo()            Sets the current record's "Video" collection
 * 
 * @package    hoanglong
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryVideo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_video');
        $this->hasColumn('idcategory_video', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Video', array(
             'local' => 'idcategory_video',
             'foreign' => 'idcategory_video_idcategory_video'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}