<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Gallery', 'doctrine');

/**
 * BaseGallery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idgallery
 * @property string $name
 * @property string $url
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property integer $category_gallery_idcategory_about_us
 * @property integer $priority
 * @property CategoryGallery $CategoryGallery
 * 
 * @method integer         getIdgallery()                            Returns the current record's "idgallery" value
 * @method string          getName()                                 Returns the current record's "name" value
 * @method string          getUrl()                                  Returns the current record's "url" value
 * @method timestamp       getCreatedAt()                            Returns the current record's "created_at" value
 * @method timestamp       getUpdatedAt()                            Returns the current record's "updated_at" value
 * @method integer         getCategoryGalleryIdcategoryAboutUs()     Returns the current record's "category_gallery_idcategory_about_us" value
 * @method integer         getPriority()                             Returns the current record's "priority" value
 * @method CategoryGallery getCategoryGallery()                      Returns the current record's "CategoryGallery" value
 * @method Gallery         setIdgallery()                            Sets the current record's "idgallery" value
 * @method Gallery         setName()                                 Sets the current record's "name" value
 * @method Gallery         setUrl()                                  Sets the current record's "url" value
 * @method Gallery         setCreatedAt()                            Sets the current record's "created_at" value
 * @method Gallery         setUpdatedAt()                            Sets the current record's "updated_at" value
 * @method Gallery         setCategoryGalleryIdcategoryAboutUs()     Sets the current record's "category_gallery_idcategory_about_us" value
 * @method Gallery         setPriority()                             Sets the current record's "priority" value
 * @method Gallery         setCategoryGallery()                      Sets the current record's "CategoryGallery" value
 * 
 * @package    hoanglong
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGallery extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gallery');
        $this->hasColumn('idgallery', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('url', 'string', 120, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'gallery.jpg',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 120,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('category_gallery_idcategory_about_us', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('priority', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CategoryGallery', array(
             'local' => 'category_gallery_idcategory_about_us',
             'foreign' => 'idcategory_gallery'));
    }
}