<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CategoryService', 'doctrine');

/**
 * BaseCategoryService
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idcategory_service
 * @property string $name
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $Service
 * 
 * @method integer             getIdcategoryService()  Returns the current record's "idcategory_service" value
 * @method string              getName()               Returns the current record's "name" value
 * @method timestamp           getCreatedAt()          Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()          Returns the current record's "updated_at" value
 * @method Doctrine_Collection getService()            Returns the current record's "Service" collection
 * @method CategoryService     setIdcategoryService()  Sets the current record's "idcategory_service" value
 * @method CategoryService     setName()               Sets the current record's "name" value
 * @method CategoryService     setCreatedAt()          Sets the current record's "created_at" value
 * @method CategoryService     setUpdatedAt()          Sets the current record's "updated_at" value
 * @method CategoryService     setService()            Sets the current record's "Service" collection
 * 
 * @package    hoanglong
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryService extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_service');
        $this->hasColumn('idcategory_service', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Service', array(
             'local' => 'idcategory_service',
             'foreign' => 'category_service_idcategory_service'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}