<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Schedule', 'doctrine');

/**
 * BaseSchedule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idschedule
 * @property string $fullname
 * @property integer $age
 * @property time $time
 * @property date $date
 * @property string $description
 * 
 * @method integer  getIdschedule()  Returns the current record's "idschedule" value
 * @method string   getFullname()    Returns the current record's "fullname" value
 * @method integer  getAge()         Returns the current record's "age" value
 * @method time     getTime()        Returns the current record's "time" value
 * @method date     getDate()        Returns the current record's "date" value
 * @method string   getDescription() Returns the current record's "description" value
 * @method Schedule setIdschedule()  Sets the current record's "idschedule" value
 * @method Schedule setFullname()    Sets the current record's "fullname" value
 * @method Schedule setAge()         Sets the current record's "age" value
 * @method Schedule setTime()        Sets the current record's "time" value
 * @method Schedule setDate()        Sets the current record's "date" value
 * @method Schedule setDescription() Sets the current record's "description" value
 * 
 * @package    hoanglong
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSchedule extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('schedule');
        $this->hasColumn('idschedule', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('fullname', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('age', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('time', 'time', null, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}