<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CategoryAboutUs', 'doctrine');

/**
 * BaseCategoryAboutUs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idcategory_about_us
 * @property string $name
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $AboutUs
 * 
 * @method integer             getIdcategoryAboutUs()   Returns the current record's "idcategory_about_us" value
 * @method string              getName()                Returns the current record's "name" value
 * @method timestamp           getCreatedAt()           Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()           Returns the current record's "updated_at" value
 * @method Doctrine_Collection getAboutUs()             Returns the current record's "AboutUs" collection
 * @method CategoryAboutUs     setIdcategoryAboutUs()   Sets the current record's "idcategory_about_us" value
 * @method CategoryAboutUs     setName()                Sets the current record's "name" value
 * @method CategoryAboutUs     setCreatedAt()           Sets the current record's "created_at" value
 * @method CategoryAboutUs     setUpdatedAt()           Sets the current record's "updated_at" value
 * @method CategoryAboutUs     setAboutUs()             Sets the current record's "AboutUs" collection
 * 
 * @package    hoanglong
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryAboutUs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_about_us');
        $this->hasColumn('idcategory_about_us', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AboutUs', array(
             'local' => 'idcategory_about_us',
             'foreign' => 'category_about_us_idcategory_about_us'));
    }
}