<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AboutUs', 'doctrine');

/**
 * BaseAboutUs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idabout_us
 * @property string $summary
 * @property string $content
 * @property string $image
 * 
 * @method integer getIdaboutUs()  Returns the current record's "idabout_us" value
 * @method string  getSummary()    Returns the current record's "summary" value
 * @method string  getContent()    Returns the current record's "content" value
 * @method string  getImage()      Returns the current record's "image" value
 * @method AboutUs setIdaboutUs()  Sets the current record's "idabout_us" value
 * @method AboutUs setSummary()    Sets the current record's "summary" value
 * @method AboutUs setContent()    Sets the current record's "content" value
 * @method AboutUs setImage()      Sets the current record's "image" value
 * 
 * @package    hoanglong
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAboutUs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('about_us');
        $this->hasColumn('idabout_us', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('summary', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('image', 'string', 120, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'about.jpg',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 120,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}