<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Slide', 'doctrine');

/**
 * BaseSlide
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idslide
 * @property string $name
 * @property string $images
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer   getIdslide()    Returns the current record's "idslide" value
 * @method string    getName()       Returns the current record's "name" value
 * @method string    getImages()     Returns the current record's "images" value
 * @method timestamp getCreatedAt()  Returns the current record's "created_at" value
 * @method timestamp getUpdatedAt()  Returns the current record's "updated_at" value
 * @method Slide     setIdslide()    Sets the current record's "idslide" value
 * @method Slide     setName()       Sets the current record's "name" value
 * @method Slide     setImages()     Sets the current record's "images" value
 * @method Slide     setCreatedAt()  Sets the current record's "created_at" value
 * @method Slide     setUpdatedAt()  Sets the current record's "updated_at" value
 * 
 * @package    hoanglong
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSlide extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('slide');
        $this->hasColumn('idslide', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'hoàng long',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('images', 'string', 120, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'slide.jpg',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 120,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}