<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AboutUs', 'doctrine');

/**
 * BaseAboutUs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idnews
 * @property string $images
 * @property string $title
 * @property string $summary
 * @property string $content
 * 
 * @method integer getIdnews()  Returns the current record's "idnews" value
 * @method string  getImages()  Returns the current record's "images" value
 * @method string  getTitle()   Returns the current record's "title" value
 * @method string  getSummary() Returns the current record's "summary" value
 * @method string  getContent() Returns the current record's "content" value
 * @method AboutUs setIdnews()  Sets the current record's "idnews" value
 * @method AboutUs setImages()  Sets the current record's "images" value
 * @method AboutUs setTitle()   Sets the current record's "title" value
 * @method AboutUs setSummary() Sets the current record's "summary" value
 * @method AboutUs setContent() Sets the current record's "content" value
 * 
 * @package    hoanglong
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAboutUs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('about_us');
        $this->hasColumn('idnews', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('images', 'string', 120, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'news.jpg',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 120,
             ));
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('summary', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}