<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Schedule', 'doctrine');

/**
 * BaseSchedule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idschedule
 * @property string $fullname
 * @property integer $age
 * @property string $address
 * @property string $phone
 * @property date $date
 * @property string $description
 * @property integer $status
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer   getIdschedule()  Returns the current record's "idschedule" value
 * @method string    getFullname()    Returns the current record's "fullname" value
 * @method integer   getAge()         Returns the current record's "age" value
 * @method string    getAddress()     Returns the current record's "address" value
 * @method string    getPhone()       Returns the current record's "phone" value
 * @method date      getDate()        Returns the current record's "date" value
 * @method string    getDescription() Returns the current record's "description" value
 * @method integer   getStatus()      Returns the current record's "status" value
 * @method timestamp getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp getUpdatedAt()   Returns the current record's "updated_at" value
 * @method Schedule  setIdschedule()  Sets the current record's "idschedule" value
 * @method Schedule  setFullname()    Sets the current record's "fullname" value
 * @method Schedule  setAge()         Sets the current record's "age" value
 * @method Schedule  setAddress()     Sets the current record's "address" value
 * @method Schedule  setPhone()       Sets the current record's "phone" value
 * @method Schedule  setDate()        Sets the current record's "date" value
 * @method Schedule  setDescription() Sets the current record's "description" value
 * @method Schedule  setStatus()      Sets the current record's "status" value
 * @method Schedule  setCreatedAt()   Sets the current record's "created_at" value
 * @method Schedule  setUpdatedAt()   Sets the current record's "updated_at" value
 * 
 * @package    hoanglong
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSchedule extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('schedule');
        $this->hasColumn('idschedule', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('fullname', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('age', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('address', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('phone', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}