<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FeedBack', 'doctrine');

/**
 * BaseFeedBack
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idfeed_back
 * @property string $name_customer
 * @property string $address
 * @property string $avatar
 * @property string $content
 * 
 * @method integer  getIdfeedBack()    Returns the current record's "idfeed_back" value
 * @method string   getNameCustomer()  Returns the current record's "name_customer" value
 * @method string   getAddress()       Returns the current record's "address" value
 * @method string   getAvatar()        Returns the current record's "avatar" value
 * @method string   getContent()       Returns the current record's "content" value
 * @method FeedBack setIdfeedBack()    Sets the current record's "idfeed_back" value
 * @method FeedBack setNameCustomer()  Sets the current record's "name_customer" value
 * @method FeedBack setAddress()       Sets the current record's "address" value
 * @method FeedBack setAvatar()        Sets the current record's "avatar" value
 * @method FeedBack setContent()       Sets the current record's "content" value
 * 
 * @package    hoanglong
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFeedBack extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('feed_back');
        $this->hasColumn('idfeed_back', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name_customer', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('address', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('avatar', 'string', 120, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'avatar.jpg',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 120,
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}