generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Slide
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          slide
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
      list:
        title: List Slide 1366 x 681
        batch_actions:  {}
        actions:  ~
        max_per_page: 10
        object_actions:
          _edit:  {label: Detail}
          _delete:  {label: Del}
        display: [images, name]
      filter:
        display: [name]
      form:
        display: [images, name]
      edit:    ~
      new:     ~