-- MySQL Script generated by MySQL Workbench
-- 05/23/17 00:09:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hoanglong_web
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hoanglong_web
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hoanglong_web` DEFAULT CHARACTER SET utf8 ;
USE `hoanglong_web` ;

-- -----------------------------------------------------
-- Table `hoanglong_web`.`category_about_us`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoanglong_web`.`category_about_us` (
  `idcategory_about_us` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idcategory_about_us`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoanglong_web`.`about_us`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoanglong_web`.`about_us` (
  `idnews` INT(11) NOT NULL AUTO_INCREMENT,
  `images` VARCHAR(120) NULL DEFAULT 'news.jpg',
  `title` TEXT NULL DEFAULT NULL,
  `summary` TEXT NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `category_about_us_idcategory_about_us` INT NOT NULL,
  `priority` INT NULL DEFAULT 1,
  PRIMARY KEY (`idnews`, `category_about_us_idcategory_about_us`),
  INDEX `fk_about_us_category_about_us1_idx` (`category_about_us_idcategory_about_us` ASC),
  CONSTRAINT `fk_about_us_category_about_us1`
    FOREIGN KEY (`category_about_us_idcategory_about_us`)
    REFERENCES `hoanglong_web`.`category_about_us` (`idcategory_about_us`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoanglong_web`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoanglong_web`.`admin` (
  `idadmin` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fullname` VARCHAR(120) NULL DEFAULT 'admin',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoanglong_web`.`category_news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoanglong_web`.`category_news` (
  `idcategory_news` INT(11) NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idcategory_news`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoanglong_web`.`category_service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoanglong_web`.`category_service` (
  `idcategory_service` INT(11) NOT NULL,
  `name` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idcategory_service`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoanglong_web`.`specialist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoanglong_web`.`specialist` (
  `idspecialist` INT(11) NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idspecialist`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoanglong_web`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoanglong_web`.`doctor` (
  `iddoctor` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `degree` TEXT NULL DEFAULT NULL,
  `summary` TEXT NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `avatar` VARCHAR(120) NULL DEFAULT 'doctor.jpg',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `specialist_idspecialist` INT(11) NOT NULL,
  `priority` INT NULL DEFAULT 1,
  PRIMARY KEY (`iddoctor`, `specialist_idspecialist`),
  INDEX `fk_doctor_specialist1_idx` (`specialist_idspecialist` ASC),
  CONSTRAINT `fk_doctor_specialist1`
    FOREIGN KEY (`specialist_idspecialist`)
    REFERENCES `hoanglong_web`.`specialist` (`idspecialist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoanglong_web`.`feed_back`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoanglong_web`.`feed_back` (
  `idfeed_back` INT(11) NOT NULL AUTO_INCREMENT,
  `name_customer` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(120) NULL DEFAULT 'avatar.jpg',
  `content` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `priority` INT NULL DEFAULT 1,
  PRIMARY KEY (`idfeed_back`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoanglong_web`.`category_gallery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoanglong_web`.`category_gallery` (
  `idcategory_gallery` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idcategory_gallery`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoanglong_web`.`gallery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoanglong_web`.`gallery` (
  `idgallery` INT(11) NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL DEFAULT NULL,
  `url` VARCHAR(120) NULL DEFAULT 'gallery.jpg',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `category_gallery_idcategory_about_us` INT NOT NULL,
  `priority` INT NULL DEFAULT 1,
  PRIMARY KEY (`idgallery`, `category_gallery_idcategory_about_us`),
  INDEX `fk_gallery_category_gallery1_idx` (`category_gallery_idcategory_about_us` ASC),
  CONSTRAINT `fk_gallery_category_gallery1`
    FOREIGN KEY (`category_gallery_idcategory_about_us`)
    REFERENCES `hoanglong_web`.`category_gallery` (`idcategory_gallery`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoanglong_web`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoanglong_web`.`news` (
  `idnews` INT(11) NOT NULL AUTO_INCREMENT,
  `images` VARCHAR(120) NULL DEFAULT 'news.jpg',
  `title` TEXT NULL DEFAULT NULL,
  `summary` TEXT NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `category_news_idcategory` INT(11) NOT NULL,
  `priority` INT NULL DEFAULT 1,
  PRIMARY KEY (`idnews`, `category_news_idcategory`),
  INDEX `fk_news_category_news_idx` (`category_news_idcategory` ASC),
  CONSTRAINT `fk_news_category_news`
    FOREIGN KEY (`category_news_idcategory`)
    REFERENCES `hoanglong_web`.`category_news` (`idcategory_news`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoanglong_web`.`ajax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoanglong_web`.`schedule` (
  `idschedule` INT(11) NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(45) NULL DEFAULT NULL,
  `age` INT(11) NULL DEFAULT NULL,
  `address` TEXT NULL DEFAULT NULL,
  `phone` VARCHAR(15) NULL,
  `date` DATE NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `status` INT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idschedule`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoanglong_web`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoanglong_web`.`service` (
  `idnews` INT(11) NOT NULL AUTO_INCREMENT,
  `images` VARCHAR(120) NULL DEFAULT 'news.jpg',
  `title` TEXT NULL DEFAULT NULL,
  `summary` TEXT NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `priority` INT NULL DEFAULT 1,
  `category_service_idcategory_service` INT(11) NOT NULL,
  PRIMARY KEY (`idnews`, `category_service_idcategory_service`),
  INDEX `fk_service_category_service1_idx` (`category_service_idcategory_service` ASC),
  CONSTRAINT `fk_service_category_service1`
    FOREIGN KEY (`category_service_idcategory_service`)
    REFERENCES `hoanglong_web`.`category_service` (`idcategory_service`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
