-- MySQL Script generated by MySQL Workbench
-- 04/28/17 23:34:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hoanglong_web
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hoanglong_web
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hoanglong_web` DEFAULT CHARACTER SET utf8 ;
USE `hoanglong_web` ;

-- -----------------------------------------------------
-- Table `hoanglong_web`.`about_us`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoanglong_web`.`about_us` (
  `idabout_us` INT(11) NOT NULL AUTO_INCREMENT,
  `summary` TEXT NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `image` VARCHAR(120) NULL DEFAULT 'about.jpg',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`idabout_us`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoanglong_web`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoanglong_web`.`category` (
  `idcategory` INT(11) NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`idcategory`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoanglong_web`.`specialist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoanglong_web`.`specialist` (
  `idspecialist` INT(11) NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`idspecialist`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoanglong_web`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoanglong_web`.`doctor` (
  `iddoctor` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `degree` TEXT NULL DEFAULT NULL,
  `summary` TEXT NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `specialist_idspecialist` INT(11) NOT NULL,
  `avatar` VARCHAR(120) NULL DEFAULT 'doctor.jpg',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`iddoctor`, `specialist_idspecialist`),
  INDEX `doctor_specialist_idspecialist_specialist_idspecialist` (`specialist_idspecialist` ASC),
  CONSTRAINT `doctor_specialist_idspecialist_specialist_idspecialist`
    FOREIGN KEY (`specialist_idspecialist`)
    REFERENCES `hoanglong_web`.`specialist` (`idspecialist`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoanglong_web`.`feed_back`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoanglong_web`.`feed_back` (
  `idfeed_back` INT(11) NOT NULL AUTO_INCREMENT,
  `name_customer` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(120) NULL DEFAULT 'avatar.jpg',
  `content` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`idfeed_back`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoanglong_web`.`gallery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoanglong_web`.`gallery` (
  `idgallery` INT(11) NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL DEFAULT NULL,
  `url` VARCHAR(120) NULL DEFAULT 'gallery.jpg',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`idgallery`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoanglong_web`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoanglong_web`.`news` (
  `idnews` INT(11) NOT NULL AUTO_INCREMENT,
  `images` VARCHAR(120) NULL DEFAULT 'news.jpg',
  `summary` TEXT NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `category_idcategory` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`idnews`, `category_idcategory`),
  INDEX `news_category_idcategory_category_idcategory` (`category_idcategory` ASC),
  CONSTRAINT `news_category_idcategory_category_idcategory`
    FOREIGN KEY (`category_idcategory`)
    REFERENCES `hoanglong_web`.`category` (`idcategory`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoanglong_web`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoanglong_web`.`schedule` (
  `idschedule` INT(11) NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(45) NULL DEFAULT NULL,
  `age` INT(11) NULL DEFAULT NULL,
  `time` VARCHAR(10) NULL DEFAULT NULL,
  `date` VARCHAR(10) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`idschedule`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
