generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Specialist
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          specialist
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name: {label: Tên chuyên khoa}
        order_item: {label: Thứ tự}
      list:
        title: Danh sách các chuyên khoa
        batch_actions:  {}
        actions:  ~
        sort: [order_item, asc]
        max_per_page: 10
        object_actions:
          _edit:  {label: Detail}
          _delete:  {label: Del}
        display: [order_item, name, updated_at]
      filter:
        class: false
      form:
        display: [name]
      edit:    ~
      new:     ~
