<?php

/**
 * AboutUsTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AboutUsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AboutUsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AboutUs');
    }

    public static function getAllAboutUs()
    {
        $query = AboutUsTable::getInstance()
            ->createQuery('c')
            ->select('c.idnews, c.title as name')
            ->fetchArray();
        return $query;
    }

    public static function getAboutUsMenu()
    {
        $query = AboutUsTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->where('c.category_about_us_idcategory_about_us = ?', 0)
            ->fetchArray();
        return $query;
    }

    public static function getAllAboutUsByCategory($id)
    {
        $query = AboutUsTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->where('category_about_us_idcategory_about_us = ?', $id)
            ->fetchArray();
        return $query;
    }

    public static function getAboutUsHomepage()
    {
        $query = AboutUsTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->where('c.priority = 5')
            ->fetchOne();
        return $query;
    }

    public static function getAboutRelatedWith($id, $limit = 4)
    {
        $query = AboutUsTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->where('c.idnews != ?', $id)
            ->limit($limit)
            ->orderBy('RAND()')
            ->fetchArray();
        return $query;
    }

    public static function getAboutUsById($id)
    {
        $query = AboutUsTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->where('c.idnews = ?', $id)
            ->fetchOne();
        return $query;
    }

    public static function getAllNews($limit = 5, $offset = 0, $category = NULL)
    {
        if ($category == NULL) {
            $query = AboutUsTable::getInstance()
                ->createQuery('c')
                ->select('c.*')
                ->where('c.idnews != 1')
                ->addWhere('c.idnews != 2')
                ->limit($limit)
                ->offset($offset)
                ->orderBy("c.idnews")
                ->groupBy('c.idnews')
                ->fetchArray();
        } else {
            $query = AboutUsTable::getInstance()
                ->createQuery('c')
                ->select('c.*')
                ->limit($limit)
                ->offset($offset)
                ->where('c.category_about_us_idcategory_about_us = ?', $category)
                ->addWhere('c.idnews != 1')
                ->addWhere('c.idnews != 2')
                ->orderBy("c.idnews")
                ->groupBy('c.idnews')
                ->fetchArray();
        }
        return $query;
    }
    public static function getTotalPages(){
        $count = AboutUsTable::getInstance()
            ->createQuery('c')
            ->select('count(c.idnews) as count')
            ->where('c.idnews != 1')
            ->addWhere('c.idnews != 2')
            ->fetchArray();
        return $count[0]['count'];
    }
    public static function getAboutUsRelated($limit = 4)
    {
        $query = AboutUsTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->limit($limit)
            ->orderBy('RAND()')
            ->fetchArray();
        return $query;
    }
}