<?php

/**
 * AdminTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdminTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdminTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Admin');
    }

    public static function getUserByUsername($username, $password)
    {
        $query = AdminTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->where('c.username = ?', $username)
            ->addWhere('c.password = ?', $password)
            ->fetchOne();
        return $query;
    }

    public static function getByUsername($username)
    {
        $query = AdminTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->where('c.username = ?', $username)
            ->fetchOne();
        return $query;
    }
}