<?php

/**
 * CategoryAboutUsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryAboutUsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryAboutUsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryAboutUs');
    }
    public static function getMenuTree()
    {
        $result = [];
        //lay tat ca cac category
        $query = CategoryAboutUsTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->fetchArray();
        //duyet tat ca cac category ghep cac bai viet vao subcategory
        foreach ($query as $key => $value) {
            $parent = $value['idcategory_about_us'];
            //get tat ca tin tuc trong subcategory
            $arr = AboutUsTable::getAllAboutUsByCategory($parent);
            $data = [];
            if (count($arr) > 0) {
                $data = ["idcategory_about_us" => $value["idcategory_about_us"], "name" => $value["name"], "child" => $arr];
            } else {
                $data = ["idcategory_about_us" => $value["idcategory_about_us"], "name" => $value["name"]];
            }
            if($key == 0){
                $result[$key + 1] = $data;
            }else{
                array_push($result[1]['child'],$data);
            }
        }
        //get doctor
        $doctors = DoctorTable::getAllDoctor();
        array_push($result[1]['child'],["idcategory_about_us" => $value["idcategory_about_us"], "name" => "Danh sách bác sĩ", "child" => $doctors]);

        return $result;
    }
    public static function getAllCategory()
    {
        $query = CategoryAboutUsTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->fetchArray();
        return $query;
    }
}