<?php

/**
 * CategoryGalleryTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryGalleryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryGalleryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryGallery');
    }

    public static function getMenuTree()
    {
        $result = [];
        //lay tat ca cac category
        $query = CategoryGalleryTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->fetchArray();
        //duyet tat ca cac category ghep cac bai viet vao subcategory
        foreach ($query as $key => $value) {
            $parent = $value['idcategory_gallery'];
            //get tat ca tin tuc trong subcategory
            $arr = GalleryTable::getAllGalleryByCategory($parent);
            $data = ["idcategory_gallery" => $value["idcategory_gallery"], "name" => $value["name"], "child" => $arr];
            if ($key == 0) {
                $result[$key + 1] = $data;
            } else {
                array_push($result[1]['child'], $data);
            }
        }
        return $result;
    }
    public static function getAllCategory($limit, $offset){
        $query = CategoryGalleryTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->where('c.idcategory_gallery != ?',0)
            ->limit($limit)
            ->offset($offset)
            ->fetchArray();
        $count = 0;
        foreach($query as $value){
            $id = $value['idcategory_gallery'];
            $gallery_first = GalleryTable::getImagesByCategory($id,1000);
            $query[$count]['images'] = $gallery_first;
            $query[$count++]['number'] = count($gallery_first);
        }
        return $query;
    }

    public static function getCategoryById($id){
        $query = CategoryGalleryTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->where('c.idcategory_gallery = ?',$id)
            ->fetchOne();
        return $query;
    }
}