<?php

/**
 * CategoryServiceTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryServiceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryServiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryService');
    }

    public static function getAllCategory()
    {
        $query = CategoryServiceTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->fetchArray();
        return $query;
    }

    public static function getMenuTree()
    {
        $result = [];
        //lay tat ca cac category
        $query = CategoryServiceTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->fetchArray();
        //duyet tat ca cac category ghep cac bai viet vao subcategory
        foreach ($query as $key => $value) {
            $parent = $value['idcategory_service'];
            //get tat ca tin tuc trong subcategory
            $arr = ServiceTable::getAllServiceByCategoryService($parent);
            $data = [];
            if (count($arr) > 0) {
                $data = ["idcategory_service" => $value["idcategory_service"], "name" => $value["name"], "child" => $arr];
            } else {
                $data = ["idcategory_service" => $value["idcategory_service"], "name" => $value["name"]];
            }
            if($key == 0){
                $result[$key + 1] = $data;
            }else{
                array_push($result[1]['child'],$data);
            }
        }
        return $result;
    }
}