<?php

/**
 * CategoryVideoTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryVideoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryVideo');
    }

    public static function getMenuTree()
    {
        $result = [];
        //lay tat ca cac category
        $query = CategoryVideoTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->fetchArray();
        //duyet tat ca cac category ghep cac bai viet vao subcategory
        foreach ($query as $key => $value) {
            $parent = $value['idcategory_video'];
            //get tat ca tin tuc trong subcategory
            $arr = VideoTable::getAllGalleryByCategory($parent);
            $data = ["idcategory_video" => $value["idcategory_video"], "name" => $value["name"], "child" => $arr];
            if ($key == 0) {
                $result[$key + 1] = $data;
            } else {
                array_push($result[1]['child'], $data);
            }
        }
        return $result;
    }

    public static function getAllCategory()
    {
        $query = CategoryVideoTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->where('c.idcategory_video != ?', 0)
            ->fetchArray();
        return $query;
    }
}