<?php

/**
 * DoctorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DoctorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DoctorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Doctor');
    }
    public static function getAllDoctor()
    {
        $query = DoctorTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->fetchArray();
        return $query;
    }
    public static function getAllDoctorMobile()
    {
        $query = DoctorTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->fetchArray();
        return $query;
    }
    public static function getDoctorHomepage($limit = 4)
    {
        $query = DoctorTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->limit($limit)
            ->orderBy('c.updated_at')
            ->fetchArray();
        return $query;
    }
    public static function getDoctorById($id)
    {
        $query = DoctorTable::getInstance()
            ->createQuery('c')
            ->select('c.*, special.*')
            ->leftJoin('c.Specialist as special')
            ->where("c.iddoctor = ?",$id)
            ->fetchOne();
        return $query;
    }
}