<?php

/**
 * erviceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class erviceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object erviceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ervice');
    }
}