<?php

/**
 * FeedBackTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FeedBackTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FeedBackTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FeedBack');
    }
    public static function getFeedbackHomepage($limit = 3)
    {
        $query = FeedBackTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->limit($limit)
            ->fetchArray();
        return $query;
    }
}