<?php

/**
 * NewsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('News');
    }
    public static function getAllNewsByCategory($id)
    {
        $query = NewsTable::getInstance()
            ->createQuery('c')
            ->select('c.idnews, c.title, c.category_news_idcategory')
            ->where('category_news_idcategory = ?',$id)
            ->fetchArray();
        return $query;
    }
}