<?php

/**
 * NewsTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('News');
    }

    public static function getAllNewsByCategory($id)
    {
        $query = NewsTable::getInstance()
            ->createQuery('c')
            ->select('c.idnews, c.title, c.category_news_idcategory')
            ->where('category_news_idcategory = ?', $id)
            ->fetchArray();
        return $query;
    }

    public static function getNewsHomepage($limit = 4)
    {
        $query = NewsTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->limit($limit)
            ->fetchArray();
        return $query;
    }

    public static function getNewsWhyChooseUs($limit = 3)
    {
        $query = NewsTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->limit($limit)
            ->where('c.priority = 2')
            ->fetchArray();
        return $query;
    }

    public static function getAllNews($limit = 5, $offset = 0, $category = NULL)
    {
        if ($category == NULL) {
            $query = NewsTable::getInstance()
                ->createQuery('c')
                ->select('c.*')
                ->limit($limit)
                ->offset($offset)
                ->orderBy("c.idnews")
                ->groupBy('c.idnews')
                ->fetchArray();
        } else {
            $query = NewsTable::getInstance()
                ->createQuery('c')
                ->select('c.*')
                ->limit($limit)
                ->offset($offset)
                ->where('c.category_news_idcategory = ?', $category)
                ->orderBy("c.idnews")
                ->groupBy('c.idnews')
                ->fetchArray();
        }
        return $query;
    }

    public static function getTotalPages(){
        $count = NewsTable::getInstance()
            ->createQuery('c')
            ->select('count(c.idnews) as count')
            ->fetchArray();
        return $count[0]['count'];
    }

    public static function getNewsById($id)
    {
        $query = NewsTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->where('c.idnews = ?', $id)
            ->fetchOne();
        return $query;
    }

    public static function getNewsRelatedWith($id, $limit = 4)
    {
        $query = NewsTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->where('c.idnews != ?', $id)
            ->limit($limit)
            ->orderBy('RAND()')
            ->fetchArray();
        return $query;
    }
}