<?php

/**
 * ScheduleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScheduleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScheduleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Schedule');
    }

    public static function getScheduleById($id)
    {
        $query = ScheduleTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->where('c.idschedule = ?', $id)
            ->fetchOne();
        return $query;
    }
    public static function getAllCategory($limit = 5)
    {
        $query = ScheduleTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->limit($limit)
            ->orderBy('c.updated_at desc')
            ->fetchArray();
        return $query;
    }

}