<?php

/**
 * ServiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServiceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Service');
    }

    public static function getAllServiceByCategoryService($id)
    {
        $query = ServiceTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->where('c.category_service_idcategory_service = ?',$id)
            ->fetchArray();
        return $query;
    }

}