<?php

/**
 * ServiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServiceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Service');
    }

    public static function getAllServiceByCategoryService($id)
    {
        $query = ServiceTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->where('c.category_service_idcategory_service = ?',$id)
            ->fetchArray();
        return $query;
    }

    public static function getAllService(){
        $query = ServiceTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->fetchArray();
        return $query;
    }

    public static function getServiceById($id)
    {
        $query = ServiceTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->where('c.idnews = ?', $id)
            ->fetchOne();
        return $query;
    }

    public static function getServiceRelatedWith($id, $limit = 4)
    {
        $query = ServiceTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->where('c.idnews != ?', $id)
            ->limit($limit)
            ->orderBy('RAND()')
            ->fetchArray();
        return $query;
    }
}