<?php

/**
 * SlideTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SlideTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SlideTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Slide');
    }
    public static function getAllSlide($limit = 3)
    {
        $query = SlideTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->limit($limit)
            ->fetchArray();
        return $query;
    }
}