<?php

/**
 * SpecialistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SpecialistTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SpecialistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Specialist');
    }

    public static function getAllCategory()
    {
        $query = SpecialistTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->orderBy('c.order_item')
            ->fetchArray();
        return $query;
    }
}