<?php

/**
 * VideoTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VideoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Video');
    }

    public static function getAllGalleryByCategory($id)
    {
        $query = VideoTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->where('category_video_idcategory_video = ?', $id)
            ->fetchArray();
        return $query;
    }

    public static function getAllGallery($limit, $offset)
    {
        $query = VideoTable::getInstance()
            ->createQuery('c')
            ->select('c.*')
            ->limit($limit)
            ->offset($offset)
            ->fetchArray();
        return $query;
    }
    public static function getTotalPages(){
        $count = VideoTable::getInstance()
            ->createQuery('c')
            ->select('count(*) as count')
            ->fetchArray();
        return $count[0]['count'];
    }
}