generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Gallery
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          gallery
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name: {label: Tên}
        url:  {label: Ảnh}
      list:
        title: Danh sách ảnh
        batch_actions:  {}
        actions:  ~
        sort: [updated_at, desc]
        max_per_page: 10
        object_actions:
          _edit:  {label: Detail}
          _delete:  {label: Del}
        display: [name, url]
      filter:
        class: false
      form:
        display: [name, url]
      edit:    ~
      new:     ~
