# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing
detail_list_gallery:
  url:   /thu-vien-anh-phong-kham/:id/:total
  param: { module: gallery, action: detail, id: '', total: ''}
list_gallery:
  url:   /thu-muc-anh-phong-kham
  param: { module: gallery, action: index}
detail_list_gallery_ipad:
  url:   /ipad/thu-vien-anh-phong-kham/:id/:total
  param: { module: galleryipad, action: detail, id: '', total: ''}
list_gallery_ipad:
  url:   /ipad/thu-muc-anh-phong-kham
  param: { module: galleryipad, action: index}
detail_list_gallery_mobile:
  url:   /m/thu-vien-anh-phong-kham/:id/:total
  param: { module: gallerymobile, action: detail, id: '', total: ''}
list_gallery_mobile:
  url:   /m/thu-muc-anh-phong-kham
  param: { module: gallerymobile, action: index}
list_video:
  url:   /thu-muc-video-phong-kham/:idvideo
  param: { module: video, action: index, idvideo: ''}
detail_service:
  url:   /dich-vu/:idservice/:title
  param: { module: news, action: service, idservice: '', title: '' }
detail_service_ipad:
  url:   /ipad/dich-vu/:idservice/:title
  param: { module: newsipad, action: service, idservice: '', title: '' }
detail_service_mobile:
  url:   /m/dich-vu/:idservice/:title
  param: { module: newsmobile, action: service, idservice: '', title: '' }
detail_about_us:
  url:   /gioi-thieu-ve-hoang-long/:idaboutus/:title
  param: { module: aboutus, action: detail, idaboutus: '', title: '' }
detail_about_us_ipad:
  url:   /ipad/gioi-thieu-ve-hoang-long/:idaboutus/:title
  param: { module: aboutusipad, action: detail, idaboutus: '', title: '' }
detail_about_us_mobile:
  url:   /m/gioi-thieu-ve-hoang-long/:idaboutus/:title
  param: { module: aboutusm, action: detail, idaboutus: '', title: '' }
list_about_us:
  url:   /cac-bai-viet-theo-chu-de/:idcategory
  param: { module: aboutus, action: index, idcategory: '' }
list_about_us_ipad:
  url:   /ipad/cac-bai-viet-theo-chu-de/:idcategory
  param: { module: aboutusipad, action: index, idcategory: '' }
list_about_us_mobile:
  url:   /m/cac-bai-viet-theo-chu-de/:idcategory
  param: { module: aboutusm, action: index, idcategory: '' }
contact:
  url:   /lien-he
  param: { module: site, action: contact }
contact_ipad:
  url:   /ipad/lien-he
  param: { module: siteipad, action: contact}
contact_mobile:
  url:   /m/lien-he
  param: { module: sitemobile, action: contact }
make_schedue:
  url:   /make-schedule
  param: { module: ajax, action: createSchedule }
doctor:
  url:   /doi-ngu-chuyen-gia
  param: { module: doctors, action: index}
detail_doctor:
  url:   /chuyen-gia/:iddoctor/:name
  param: { module: doctors, action: detail, iddoctor: '', name: '' }
doctor_ipad:
  url:   /ipad/bac-si
  param: { module: doctorsipad, action: index}
detail_doctor_ipad:
  url:   /ipad/bac-si/:iddoctor/:name
  param: { module: doctorsipad, action: detail, iddoctor: '', name: '' }
doctor_mobile:
  url:   /m/bac-si
  param: { module: doctorsmobile, action: index}
detail_doctor_mobile:
  url:   /m/bac-si/:iddoctor/:name
  param: { module: doctorsmobile, action: detail, iddoctor: '', name: '' }
list_news:
  url:   /danh-sach-tin-tuc/:idcategory/:name
  param: { module: news, action: index, idcategory: '', name: '' }
detail_news:
  url:   /tin-tuc-hoang-long/:idnews/:title
  param: { module: news, action: detail, idnews: '', title: '' }
list_news_ipad:
  url:   /ipad/danh-sach-tin-tuc
  param: { module: newsipad, action: index }
detail_news_ipad:
  url:   /ipad/tin-tuc-hoang-long/:idnews
  param: { module: newsipad, action: detail, idnews: '' }
list_news_mobile:
  url:   /m/danh-sach-tin-tuc
  param: { module: newsmobile, action: index }
detail_news_mobile:
  url:   /m/tin-tuc-hoang-long/:idnews/:title
  param: { module: newsmobile, action: detail, idnews: '',  title: ''  }
# default rules
homepage:
  url:   /
  param: { module: homepage, action: index }
homepage_ip:
  url:   /ipad
  param: { module: homeipad, action: index }
homepage_m:
  url:   /m
  param: { module: homemobile, action: index }
# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
