# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing
detail_list_gallery:
  url:   /thu-vien-anh-phong-kham/:id
  param: { module: gallery, action: detail, id: ''}
list_gallery:
  url:   /thu-muc-anh-phong-kham
  param: { module: gallery, action: index}
detail_list_video:
  url:   /thu-vien-video-phong-kham
  param: { module: video, action: detail}
list_video:
  url:   /thu-muc-video-phong-kham
  param: { module: video, action: index}
detail_service:
  url:   /dich-vu/:idservice/:title
  param: { module: news, action: service, idservice: '', title: '' }
detail_about_us:
  url:   /gioi-thieu-ve-hoang-long/:idaboutus/:title
  param: { module: aboutus, action: detail, idaboutus: '', title: '' }
list_about_us:
  url:   /cac-bai-viet-theo-chu-de/:idcategory
  param: { module: aboutus, action: index, idcategory: '' }
contact:
  url:   /lien-he-voi-chung-toi
  param: { module: site, action: contact }
contact_ipad:
  url:   /ipad/lien-he-voi-chung-toi
  param: { module: siteipad, action: contact }
make_schedue:
  url:   /make-schedule
  param: { module: ajax, action: createSchedule }
doctor:
  url:   /bac-si
  param: { module: doctors, action: index}
detail_doctor:
  url:   /bac-si/:iddoctor/:name
  param: { module: doctors, action: detail, iddoctor: '', name: '' }
doctor_ipad:
  url:   /ipad/bac-si
  param: { module: doctorsipad, action: index}
detail_doctor_ipad:
  url:   /ipad/bac-si/:iddoctor
  param: { module: doctorsipad, action: detail, iddoctor: '' }
list_news:
  url:   /danh-sach-tin-tuc/:idcategory/:name
  param: { module: news, action: index, idcategory: '', name: '' }
detail_news:
  url:   /tin-tuc-hoang-long/:idnews/:title
  param: { module: news, action: detail, idnews: '', title: '' }
list_news_ipad:
  url:   /ipad/danh-sach-tin-tuc
  param: { module: newsipad, action: index }
detail_news_ipad:
  url:   /ipad/tin-tuc-hoang-long/:idnews
  param: { module: newsipad, action: detail, idnews: '' }
# default rules
homepage:
  url:   /
  param: { module: homepage, action: index }
homepage_ip:
  url:   /ipad
  param: { module: homeipad, action: index }
# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
