<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/05/01 15:31:59

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=hoanglong_web',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
