generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CategoryGallery
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          category_gallery
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name: {label: Tên danh mục}
        updated_at: {label: Ngày sửa đổi}
        description: {label: Mô tả}
      list:
        title: Danh sách thư mục ảnh
        batch_actions:  {}
        actions:  ~
        sort: [updated_at, desc]
        max_per_page: 10
        object_actions:
          _edit:  {label: Detail}
          _delete:  {label: Del}
        display: [name, description, updated_at]
      filter:
        class: false
      form:
        display: [name, description]
      edit:    ~
      new:     ~
