generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Video
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          video
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name: {label: Tên video}
        url:  {label: Đường dẫn}
      list:
        title: Danh sách video
        batch_actions:  {}
        actions:  ~
        sort: [updated_at, desc]
        max_per_page: 10
        object_actions:
          _edit:  {label: Detail}
          _delete:  {label: Del}
        display: [name, url, description]
      filter:
        class: false
      form:
        display: [name, url, description, category_video_idcategory_video]
      edit:    ~
      new:     ~
