generator:
  class: sfDoctrineGenerator
  param:
    model_class:           News
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          news
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        category_idcategory: {label: Category}
      list:
        title: List News
        batch_actions:  {}
        actions:  ~
        sort: [updated_at, desc]
        max_per_page: 10
        object_actions:
          _edit:  {label: Detail}
          _delete:  {label: Del}
        display: [title, summary, content, images, updated_at]
      filter:
        display:  [title]
      form:
        display: [title, summary, content, images, category_idcategory]
      edit:    ~
      new:     ~
