generator:
  class: sfDoctrineGenerator
  param:
    model_class:           News
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          news
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        category_idcategory: {label: Chuyên mục}
        images: {label: Ảnh minh họa}
        priority: {label: Nơi hiển thị}
        title: {label: Tiêu đề}
        summary: {label: Tóm tắt}
        updated_at: {label: Cập nhật hồi}
      list:
        title: Danh sách tin tức
        batch_actions:  {}
        actions:  ~
        sort: [updated_at, desc]
        max_per_page: 10
        object_actions:
          _edit:  {label: Detail}
          _delete:  {label: Del}
        display: [title, summary, images, updated_at, priority]
      filter:
        display:  [title, priority]
      form:
        display: [title, summary, content, images, category_news_idcategory, priority]
      edit:    ~
      new:     ~
