generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Doctor
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          doctor
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name: {label: Tên bác sĩ}
        degree: {label: Học vị}
        summary:  {label: Sơ lược}
        content:  {label: Thông tin chi tiết}
        specialist_idspecialist: {label: Chuyên khoa}
        avatar: {Ảnh chân dung}
      list:
        title: Danh sách bác sĩ
        batch_actions:  {}
        actions:  ~
        sort: [updated_at, desc]
        max_per_page: 10
        object_actions:
          _edit:  {label: Detail}
          _delete:  {label: Del}
        display: [name, avatar, content, updated_at]
      filter:
        display:  [specialist_idspecialist]
      form:
        display: [name, degree, summary, content, specialist_idspecialist, avatar]
      edit:    ~
      new:     ~
